using System.Text.Json;
using System.Text.Json.Serialization;

[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(VersionResponse))]
[JsonSerializable(typeof(DataResponse))]
[JsonSerializable(typeof(QueueListResponse))]
[JsonSerializable(typeof(QueueIdRow))]
[JsonSerializable(typeof(QueuedItem))]
[JsonSerializable(typeof(CompletedItem))]
[JsonSerializable(typeof(HistoryItem))]
[JsonSerializable(typeof(List<HistoryItem>))]
[JsonSerializable(typeof(MetaResponse))]
[JsonSerializable(typeof(FormatOption))]
[JsonSerializable(typeof(List<FormatOption>))]
[JsonSerializable(typeof(PartialsResponse))]
[JsonSerializable(typeof(PartialFile))]
[JsonSerializable(typeof(ConfigResponse))]
[JsonSerializable(typeof(CheckPathResponse))]
[JsonSerializable(typeof(StatusResponse))]
[JsonSerializable(typeof(LogEntry))]
[JsonSerializable(typeof(CompletedEvent))]
[JsonSerializable(typeof(AddRequest))]
[JsonSerializable(typeof(MoveRequest))]
[JsonSerializable(typeof(SetFormatRequest))]
[JsonSerializable(typeof(SetPathRequest))]
[JsonSerializable(typeof(List<QueuedItem>))]
[JsonSerializable(typeof(List<CompletedItem>))]
[JsonSerializable(typeof(List<QueueIdRow>))]
[JsonSerializable(typeof(List<PartialFile>))]
[JsonSerializable(typeof(List<LogEntry>))]
[JsonSerializable(typeof(ConvertStatusUpdate))]
[JsonSerializable(typeof(List<ConvertStatusUpdate>))]
[JsonSerializable(typeof(ConvertPs3Response))]
[JsonSerializable(typeof(ConvertSingleRequest))]
[JsonSerializable(typeof(ConvertSingleResponse))]
[JsonSerializable(typeof(AbortResponse))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
internal partial class AppJsonContext : JsonSerializerContext;
