using System.Text.Json;
using System.Text.Json.Serialization;
using Module.Ps3Iso.Bridge;
using Module.Sync;
using Module.Sync.Bridge;

[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(VersionResponse))]
[JsonSerializable(typeof(DataResponse))]
[JsonSerializable(typeof(QueueListResponse))]
[JsonSerializable(typeof(QueueIdRow))]
[JsonSerializable(typeof(QueuedItem))]
[JsonSerializable(typeof(CompletedItem))]
[JsonSerializable(typeof(HistoryItem))]
[JsonSerializable(typeof(List<HistoryItem>))]
[JsonSerializable(typeof(MetaResponse))]
[JsonSerializable(typeof(FormatOption))]
[JsonSerializable(typeof(List<FormatOption>))]
[JsonSerializable(typeof(PartialsResponse))]
[JsonSerializable(typeof(PartialFile))]
[JsonSerializable(typeof(ConfigResponse))]
[JsonSerializable(typeof(CheckPathResponse))]
[JsonSerializable(typeof(StatusResponse))]
[JsonSerializable(typeof(LogEntry))]
[JsonSerializable(typeof(CompletedEvent))]
[JsonSerializable(typeof(AddRequest))]
[JsonSerializable(typeof(MoveRequest))]
[JsonSerializable(typeof(SetFormatRequest))]
[JsonSerializable(typeof(SetPathRequest))]
[JsonSerializable(typeof(List<QueuedItem>))]
[JsonSerializable(typeof(List<CompletedItem>))]
[JsonSerializable(typeof(List<QueueIdRow>))]
[JsonSerializable(typeof(List<PartialFile>))]
[JsonSerializable(typeof(List<LogEntry>))]
[JsonSerializable(typeof(Ps3IsoStatusEvent))]
[JsonSerializable(typeof(List<Ps3IsoStatusEvent>))]
[JsonSerializable(typeof(ConvertPs3Response))]
[JsonSerializable(typeof(ConvertSingleRequest))]
[JsonSerializable(typeof(ConvertSingleResponse))]
[JsonSerializable(typeof(AbortResponse))]
[JsonSerializable(typeof(SyncCompareResponse))]
[JsonSerializable(typeof(SyncFileInfo))]
[JsonSerializable(typeof(List<SyncFileInfo>))]
[JsonSerializable(typeof(SyncDiskInfo))]
[JsonSerializable(typeof(SyncCopyRequest))]
[JsonSerializable(typeof(SyncSetPathRequest))]
[JsonSerializable(typeof(SyncProgressEvent))]
[JsonSerializable(typeof(SyncCompletedEvent))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
internal partial class AppJsonContext : JsonSerializerContext;
