using System.Text.Json;
using System.Text.Json.Serialization;
using Module.Download.Bridge;
using Module.Core.Pipeline;
using Module.Sync;
using Module.Sync.Bridge;

[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(VersionResponse))]
[JsonSerializable(typeof(DataResponse))]
[JsonSerializable(typeof(QueueListResponse))]
[JsonSerializable(typeof(QueueIdRow))]
[JsonSerializable(typeof(QueuedItem))]
[JsonSerializable(typeof(HistoryItem))]
[JsonSerializable(typeof(List<HistoryItem>))]
[JsonSerializable(typeof(MetaResponse))]
[JsonSerializable(typeof(FormatOption))]
[JsonSerializable(typeof(List<FormatOption>))]
[JsonSerializable(typeof(PartialFile))]
[JsonSerializable(typeof(LogEntry))]
[JsonSerializable(typeof(CompletedEvent))]
[JsonSerializable(typeof(DownloadCompletedEvent))]
[JsonSerializable(typeof(DownloadProgressEvent))]
[JsonSerializable(typeof(AddRequest))]
[JsonSerializable(typeof(AddResponse))]
[JsonSerializable(typeof(DuplicateInfo))]
[JsonSerializable(typeof(List<DuplicateInfo>))]
[JsonSerializable(typeof(QueuePatchRequest))]
[JsonSerializable(typeof(QueueReorderRequest))]
[JsonSerializable(typeof(List<QueuedItem>))]
[JsonSerializable(typeof(List<QueueIdRow>))]
[JsonSerializable(typeof(List<PartialFile>))]
[JsonSerializable(typeof(List<LogEntry>))]
[JsonSerializable(typeof(PipelineStatusEvent))]
[JsonSerializable(typeof(List<PipelineStatusEvent>))]
[JsonSerializable(typeof(Ps3ConvertRequest))]
[JsonSerializable(typeof(Ps3ConvertResponse))]
[JsonSerializable(typeof(Ps3ActionRequest))]
[JsonSerializable(typeof(Ps3ActionResponse))]
[JsonSerializable(typeof(QueueExportItem))]
[JsonSerializable(typeof(List<QueueExportItem>))]
[JsonSerializable(typeof(QueueImportResponse))]
[JsonSerializable(typeof(SettingsResponse))]
[JsonSerializable(typeof(SettingRequest))]
[JsonSerializable(typeof(CheckPathResponse))]
[JsonSerializable(typeof(SyncCompareRequest))]
[JsonSerializable(typeof(SyncCompareResponse))]
[JsonSerializable(typeof(SyncFileInfo))]
[JsonSerializable(typeof(List<SyncFileInfo>))]
[JsonSerializable(typeof(SyncDiskInfo))]
[JsonSerializable(typeof(SyncCopyRequest))]
[JsonSerializable(typeof(SyncProgressEvent))]
[JsonSerializable(typeof(SyncCompletedEvent))]
[JsonSerializable(typeof(TraceStep))]
[JsonSerializable(typeof(List<TraceStep>))]
[JsonSerializable(typeof(PipelineTrace))]
[JsonSerializable(typeof(MetricsResponse))]
[JsonSerializable(typeof(EventRow))]
[JsonSerializable(typeof(List<EventRow>))]
[JsonSerializable(typeof(EventsResponse))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
internal partial class AppJsonContext : JsonSerializerContext;
